# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Backend API to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - 'Backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test backend
        working-directory: ./Backend/api-keuze-kompass-lu1
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./Backend/api-keuze-kompass-lu1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC58B69BF7ED4AFA8AE63C9E20194F1C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D7159EAA470542EBBAF6F5029B9BFDDE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C00E49D0409445784FADF48C74F7AC2 }}

      - name: 'Deploy Backend to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'KeuzeKompasBackend'
          slot-name: 'Production'
          package: .