name: Build and deploy Node.js app to Azure Web App - KeuzeKompasBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'KeuzeKompasBackend'
  AZURE_WEBAPP_PACKAGE_PATH: './Backend/api-keuze-kompass-lu1'
  NODE_VERSION: '22.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json'

      - name: Install dependencies and build
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          echo "Cleaning previous builds..."
          rm -rf dist node_modules/.cache
          echo "Installing dependencies..."
          npm install
          echo "Building application..."
          npm run build
          echo "Build output:"
          ls -la dist/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE930FC655FE4BAE8D32F0CE2A5BD73D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17D003275EC1493584662E38024FBFF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E2C5EC217577415AB43DA4ABE52116C4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
          startup-command: "npm run start"

        