# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy Node.js app to Azure Web App - KeuzeKompasBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'KeuzeKompasBackend'          # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './Backend/api-keuze-kompass-lu1'  # set this to the path to your web app project
  NODE_VERSION: '22.x'                             # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './Backend/api-keuze-kompass-lu1/package-lock.json'

    - name: npm install, build, and test
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
        echo "Cleaning previous builds..."
        rm -rf dist node_modules/.cache
        echo "Installing dependencies..."
        npm install
        echo "Building application..."
        npm run build
        echo "Checking build output..."
        ls -la dist/ || echo "No dist folder found"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE930FC655FE4BAE8D32F0CE2A5BD73D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17D003275EC1493584662E38024FBFF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E2C5EC217577415AB43DA4ABE52116C4 }}

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .